openapi: 3.0.0
info:
  title: Task API
  description: API para gestionar tareas con autenticación JWT
  version: 1.0.0
servers:
  - url: http://task.test/api
paths:
  /register:
    post:
      summary: Registra un nuevo usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
              required:
                - name
                - email
                - password
      responses:
        '201':
          description: Usuario registrado exitosamente
        '400':
          description: Error en la validación de los datos

  /login:
    post:
      summary: Inicia sesión y obtiene un token JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
              required:
                - email
                - password
      responses:
        '200':
          description: Token JWT generado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '401':
          description: Credenciales inválidas

  /logout:
    post:
      summary: Cierra sesión y revoca el token JWT
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Usuario cerrado sesión exitosamente

  /tasks:
    get:
      summary: Obtiene la lista de tareas
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de tareas
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    code:
                      type: string
                    title:
                      type: string
                    description:
                      type: string
                    status:
                      type: string
                    priority:
                      type: string
                    finality:
                      type: string

    post:
      summary: Crea una nueva tarea
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
                title:
                  type: string
                description:
                  type: string
                status:
                  type: string
                priority:
                  type: string
                finality:
                  type: string
              required:
                - code
                - title
                - status
                - priority
                - finality
      responses:
        '201':
          description: Tarea creada exitosamente
        '400':
          description: Error en la validación de los datos

  /tasks/{id}:
    get:
      summary: Obtiene una tarea específica
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: ID de la tarea
          schema:
            type: integer
      responses:
        '200':
          description: Tarea encontrada
        '404':
          description: Tarea no encontrada

    put:
      summary: Actualiza una tarea existente
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: ID de la tarea
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
                title:
                  type: string
                description:
                  type: string
                status:
                  type: string
                priority:
                  type: string
                finality:
                  type: string
              required:
                - code
                - title
                - status
                - priority
                - finality
      responses:
        '200':
          description: Tarea actualizada exitosamente
        '404':
          description: Tarea no encontrada

    delete:
      summary: Elimina una tarea existente
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in